# Generated by Django 4.0.4 on 2022-08-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kitchen Steelproduct', 'Kitchen Steelproduct'), ('Grocery', 'Grocery'), ('Vegitables', 'Vegitables'), ('Fresh Fruits', 'Fresh Fruits'), ('Snacks', 'Snacks'), ('Cold Drinks', 'Cold Drinks'), ('Dryfruits & Nuts', 'Dryfruits & Nuts'), ('Hot Drinks', 'Hot Drinks'), ('Protins', 'Protins'), ('Beauty Products', 'Beauty Products'), ('Other Home Products', 'Other Home Products')], max_length=50),
        ),
    ]
