# Generated by Django 4.0.4 on 2022-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_city_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(max_length=50, unique=True)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_purchase_date',
            field=models.DateField(blank=True),
        ),
    ]
