# Generated by Django 4.0.4 on 2022-09-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart_offer_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
