# Generated by Django 4.0.4 on 2022-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Select', 'Select'), ('Kitchen Steelproduct', 'Kitchen Steelproduct'), ('Grocery', 'Grocery'), ('Vegitables', 'Vegitables'), ('Fresh Fruits', 'Fresh Fruits'), ('Snacks', 'Snacks'), ('Cold Drinks', 'Cold Drinks'), ('Dryfruits & Nuts', 'Dryfruits & Nuts'), ('Hot Drinks', 'Hot Drinks'), ('Protins', 'Protins'), ('Beauty Products', 'Beauty Products'), ('Other Home Products', 'Other Home Products')], default='Select', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_color',
            field=models.CharField(choices=[('Select', 'Select'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'blue'), ('Indigo', 'Indigo'), ('Violet', 'Violet')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_size',
            field=models.CharField(choices=[('Select', 'Select'), ('100 Gms', '100 gms'), ('250 Gms', '250 gms'), ('500 Gms', '500 gms'), ('1 Kg', '1 kg'), ('1.5 Kg', '1.5 kg'), ('2 Kg', '2 kg')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_category',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('ACCOUNTANT', 'Accountant')], max_length=100),
        ),
    ]
