# Generated by Django 4.0.4 on 2022-09-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_orderplaced_order_date_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=5)),
                ('group_name', models.CharField(max_length=50)),
                ('g_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_code', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=5)),
                ('supplier_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=50)),
                ('supplier_email', models.EmailField(max_length=254, null=True)),
                ('gstin_no', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujurat', 'Gujurat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Assam', 'Assam'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Benga')], max_length=50, null=True)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='item_size',
            field=models.CharField(choices=[('Select', 'Select'), ('100 Gms', '100 gms'), ('250 Gms', '250 gms'), ('500 Gms', '500 gms'), ('1 Kg', '1 kg'), ('1.5 Kg', '1.5 kg'), ('2 Kg', '2 kg'), ('100 Ml', '100 Ml'), ('250 Ml', '250 Ml'), ('500 Ml', '500 Ml'), ('1 L', '1 L'), ('1.5 L', '1.5 L'), ('2 L', '2 L')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
