# Generated by Django 4.0.4 on 2022-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_color_group_size_supplier_alter_product_item_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='item_color',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='item_size',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='product',
            name='item_color',
            field=models.CharField(default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_size',
            field=models.CharField(default='Select', max_length=100),
        ),
    ]
