# Generated by Django 4.0.4 on 2022-09-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_color_color_item_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='product',
            name='item_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
