# Generated by Django 4.0.4 on 2022-10-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
