# Generated by Django 4.0.4 on 2022-10-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_group_p_group_alter_product_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P_Group',
        ),
    ]
