# Generated by Django 4.0.4 on 2022-10-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_prodgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prodgroup',
        ),
    ]
