# Generated by Django 4.0.4 on 2022-11-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_prodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
